<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    protected $fillable = ['item_id'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($model) {
            $model->nofity_item_owner();
        });
    }

    //
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function item()
    {
        return $this->belongsTo('App\Item');
    }

    public function notification()
    {
        return $this->morphMany('App\Notification', 'source');
    }

    public function notify_item_owner(){
        if($notification = Notification::create(["source" => $this, title => '商品が購入されました'])){
            $notification->devices->attach($this->item->owner->devices->pluck('id'));
            $notification->notify_once();
        }
    }
}
